services:
  - type: web
    name: my-django-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn core.wsgi:application
    envVars:
      - key: SECRET_KEY
        value: your-secret-here
      - key: DEBUG
        value: False
